site_name: Awesome UniFi
site_url: https://awesome-unifi.com
site_description: A curated list of awesome UniFi frameworks, libraries and software
site_author: Rakesh Mukundan
repo_name: Nibblecomm/awesome-unifi
repo_url: https://github.com/Nibblecomm/awesome-unifi
copyright: Copyright &copy; 2022 Nibblecomm, Inc

theme:
  name: material
  custom_dir: overrides

extra:
  analytics:
    provider: google
    property: G-ERBMT2LVS7

  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Spotipo1
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/spotipo
