site_name: Awesome UniFi
site_url: https://awesome-unifi.com
site_description: A curated list of awesome UniFi frameworks, libraries and software
site_author: Rakesh Mukundan
repo_name: Nibblecomm/awesome-unifi
repo_url: https://github.com/Nibblecomm/awesome-unifi
theme:
  name: material

extra:
  analytics:
    provider: google
    property: G-ERBMT2LVS7